id: P992A2A44
initial_creation_type: input
source_metadata:
  title: Northern Treasures Series
  language: bo
  description: 'Texts related to the so-called Northern Treasures or Jangter/Changter
    (byang gter) tradition:'
  volume:
    313618f5aba84b72a4121d89a6a6078f:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Aspiration Prayers
    090d854a3aa643aa95974b673b12d1f6:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
    60e376b7f3f1470d801c343a2d55f5e9:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Sādhanas
created_at: '2022-03-01T04:52:29.101617'
last_modified_at: '2022-03-01T04:52:29.101619'
